### ISSUE TITLE
Processing in the galway case. 

### ISSUE THREAD

**Issue by acapet** [acapet/ForCoast-SM-A2#10]
I described (#12 ) a download issue for the galway case. 

I've passed over this step with a manual download, using this script. 

```
#!/bin/bash
for day in {1..9}; do
    for hh in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23; do 
	wget http://milas.marine.ie/thredds/fileServer/IMI_ROMS_HYDRO/GALWAY_BAY_NATIVE_70M_8L_1H/ANALYSIS/galway_bay_2021110${day}${hh}.nc
    done
done
```
It gets the required file for testing for instance `./run_py.sh galway 2021-11-01 5`.

Yet, I've an error from the processing step.. 

```
python forcoast_download_yml.py -a galway -T 2021-11-01 -p 5 -d /home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/
-->Skipped

Download done.
Starting processing for ../usr/galway/config/sources.txt
python forcoast.py -y galway -T 2021-11-01 -p 5 -s [-8.927046,53.142875,-1.0] -d /home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/ 
running in 3D
Replace selected input with input from command line
Pollutant release coordinates: x0=[-8.927046], y0=[53.142875]
Start date: 2021-11-01
Simulation length: 5
Data directory: /home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/
romsfiles :/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/testdata/galway_bay_2021110100.nc
Traceback (most recent call last):
  File "forcoast.py", line 103, in <module>
    fieldset=get_roms_fields(romsfiles,run3D=options['run3D'],chunksize=False,vdiffusion=options['vdiffusion'],beaching=options['beaching'])https://github.com/acapet/ForCoast-SM-A2/issues/12
  File "/home/arthur/Desktop/DOCS/PROJECTS/FORECOAST/Pilot/SM/ForCoast-SM-A3/Processing/forcoast_loaders.py", line 106, in get_roms_fields
    fieldset=FieldSet.from_netcdf(filenames, variables, dimensions, indices=indices, vmax=1.0e36) #allow_time_extrapolation=True
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/fieldset.py", line 412, in from_netcdf
    fieldtype=fieldtype, chunksize=varchunksize, dataFiles=dFiles, **kwargs)
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/field.py", line 377, in from_netcdf
    indices, netcdf_engine)
  File "/home/arthur/miniconda3/envs/forcoastA2/lib/python3.6/site-packages/parcels/field.py", line 250, in collect_timeslices
    id_not_ordered = np.where(time[1:] < time[:-1])[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

```
Will this be related to the fact that files only contains a single step ? 

Would concatenating files before (using NCO), after download (better) or as a requirement to MI data delivery (not fan of introducing requirements to the data delivery, but that would solve the download issue), be an option to solve this ?

**Comment by acapet** [comment]
Just a mistake on my side ...
